### ISSUE TITLE
[Feature Request]: Docker 新增 dev-latest 标签

### ISSUE THREAD

**Issue by greenhat616** [EstrellaXD/Auto_Bangumi#163]
### 功能改进

我在查阅 issues 和 commits 的过程中发现，一些错误已经在 `main` 分支得到了修复，但是还没有发布到 `release` 中
  * 比如说：梦蓝字幕组的 哆啦 A 梦 的剧集识别

因此，也许我们可以考虑使用 `Github Actions` 来为 `main` 分支的提交自动推送 Docker 容器到 Dockerhub？
* 可以让用户享受到最新的修复，但同时伴随着 bug —— 用户风险自负
* 因此，为了避免用户的困扰。我们可以采用 `dev-latest` 或者 `dev` 标签用于此容器的分发。

以下是一个自动推送的实例：
```yml
name: Deploy To Dockerhub(dev)

on:
  push:
    branches: [ main ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: estrellaxd/auto_bangumi:dev-latest
          file: ./Dockerfile
```
