### ISSUE TITLE
[错误报告] WebUI 订阅新番一直返回 null

### ISSUE THREAD

**Issue by 9bingyin** [EstrellaXD/Auto_Bangumi#203]
### 当前程序版本

2.6.0

### 问题类型

WebUI

### 问题描述

webui上，同一个链接，订阅新番一直是none，但是订阅旧番是正常的
url: https://mikanani.me/RSS/Bangumi?bangumiId=2968&subgroupid=583
AB配置文件如下
```
{
    "data_version": 5.0,
    "program": {
        "sleep_time": 600,
        "rename_times": 20,
        "webui_port": 7892
    },
    "downloader": {
        "type": "qbittorrent",
        "host": "192.168.5.11:8080",
        "username": "admin",
        "password": "adminadmin",
        "path": "/downloads/Bangumi",
        "ssl": false
    },
    "rss_parser": {
        "enable": true,
        "type": "mikan",
        "token": "none",
        "custom_url": "mikanani.me",
        "enable_tmdb": false,
        "filter": [
            "720P|1280x720"
        ],
        "language": "zh"
    },
    "bangumi_manage": {
        "enable": true,
        "eps_complete": false,
        "rename_method": "pn",
        "group_tag": false,
        "remove_bad_torrent": false
    },
    "log": {
        "debug_enable": true
    },
    "proxy": {
        "enable": false,
        "type": "http",
        "host": "",
        "port": 0,
        "username": "",
        "password": ""
    },
    "notification": {
        "enable": false,
        "type": "telegram",
        "token": "",
        "chat_id": ""
    }
}
```

**Comment by EstrellaXD** [comment]
可以看下 Docker 中的 Log，我这没定位到问题

**Comment by 9bingyin** [comment]
日志会有
```
Wrong API response.
[2023-04-27 16:26:20,250] INFO      192.168.5.10:10300 - "POST /api/v1/subscribe HTTP/1.1" 200
INFO:     192.168.5.10:10300 - "POST /api/v1/subscribe HTTP/1.1" 200 OK
```

**Comment by EstrellaXD** [comment]
添加完之后 qb 里面也没新建 RSS 链接和下载规则么，目前看只有返回这边会有错误，看日志请求是没问题的

**Comment by 9bingyin** [comment]
qb 里没有新建 RSS 链接和下载规则

**Comment by 9bingyin** [comment]
这是我的 docker-compose 文件
```
version: "3.2"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=100
      - PUID=1000
      - WEBUI_PORT=8080
    volumes:
      - /mnt/user/appdata/AutoBangumi/qb_config:/config
      - /mnt/user/Media:/downloads
    ports:
      - 8080:8080
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: superng6/qbittorrent

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=100
      - PUID=1000
    networks:
      - auto_bangumi
    volumes:
      - /mnt/user/appdata/AutoBangumi/auto_bangumi/config:/app/config
      - /mnt/user/appdata/AutoBangumi/auto_bangumi/data:/app/data
    ports:
      - '7892:7892'
    dns:
      - 192.168.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

networks:
  auto_bangumi:
volumes:
  qb_config:
    external: false
```
