### ISSUE TITLE
[Feature Request] 未检测到qBitTorrent时，间隔指定时间后重启AutoBangumi

### ISSUE THREAD

**Issue by AUKcl** [EstrellaXD/Auto_Bangumi#429]
### 功能改进

这两天给服务器新增了UPS，配置完测试的时候发现，群晖在接受UPS断电信号进行安全关机，在来电自启后，Docker配置开机自启的全部容器会在同一时间启动，无法指定开启顺序及间隔时间，而Docker配置的qBitTorrent开启至正常使用的时间远大于AutoBangumi，这直接导致了AutoBangumi开启后无法正确连接至qBitTorrent，也就无法正常执行番剧自动下载了，需要等qBitTorrent能够正常访问后，再手动登陆AutoBangumi的WEB UI进行服务重启；
这样的话，以后出差时，家里一旦停电就需要进行远程重启，非常的麻烦；

**Comment by xinnjie** [comment]
如果使用 docker compose 部署，可以指定 qbittorrent 服务已经可以提供正常服务后再拉起 autobangumi
例子：
```
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    hostname: qbittorrent
      #user: 1000:1000
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8081
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${path-to-config}:/config
      - ${path-to-download:}/downloads 
    network_mode: bridge
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8081"]

  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
      # user: 1000:1000
    depends_on:
      qbittorrent:
        condition: service_healthy
    volumes:
      - ${path-to-config}:/app/config
      - ${path-to-data}:/app/data
    network_mode: bridge
    ports:
      - 7892:7892
    dns:
      - 223.5.5.5
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - AB_DOWNLOADER_HOST=qbittorrent:8081
```

注意替换 `${path-to-config}` `${path-to-config}` `${path-to-data}` 这几个本地目录名
