### ISSUE TITLE
[Discussion] 下载器连接错误，看了文档，还是没解决

### ISSUE THREAD

**Issue by xiatian12345** [EstrellaXD/Auto_Bangumi#479]
## 项目讨论

日志：
[2023-09-27 16:26:35] INFO:     Config loaded
[2023-09-27 16:26:35] INFO:     Config updated
[2023-09-27 16:26:35] INFO:     Config loaded
[2023-09-27 16:26:37] ERROR     [Checker] Downloader connect failed.
[2023-09-27 16:26:37] WARNING:  Program failed to start.

### 下载器配置------->
下载器类型
qbittorrent
下载器地址
172.17.0.1:8080
用户名
admin
密码
adminadmin
下载地址
/downloads/Bangumi

autobangumi docker compose文件------->
```yaml
version: "3.8"

services:
  AutoBangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: AutoBangumi
    volumes:
      - AutoBangumi_config:/app/config
      - AutoBangumi_data:/app/data
    ports:
      - 7892:7892
    restart: unless-stopped
    dns:
      - 223.5.5.5
    network_mode: bridge

volumes:
    AutoBangumi_config:
        external: true
        name: AutoBangumi_config
    AutoBangumi_data:
        external: true
        name: AutoBangumi_data

qbittorrent docker compose 文件------->
version: "2"
services:
  qbittorrent:
    image: superng6/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=501
      - PGID=20
      - TZ=Asia/Shanghai
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_data:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
volumes:
  qbittorrent_config:
    external: true
    name: qbittorrent_config
  qbittorrent_data:
    external: true
    name: qbittorrent_data
```

另外------->
本地浏览器可通过http://localhost:8080/正常访问qBittorrent WebUI
docker 网络相关信息如下
➜  autobangumi docker network ls
NETWORK ID     NAME                  DRIVER    SCOPE
cf48a68df2b9   bridge                bridge    local
21191745a5f1   host                  host      local
067e7c691f9b   none                  null      local
e6b816c0a9bd   qbittorrent_default   bridge    local
➜  autobangumi docker network inspect cf48a68df2b9
```json
[
    {
        "Name": "bridge",
        "Id": "cf48a68df2b9285a8046bd55b6116a322410f123008867a1d3c622ceebd4f847",
        "Created": "2023-09-26T18:31:40.114962113Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0c5335c7a1f3c82819b7ccf75dde973ae6d538ac786821943c2551bb42fed6af": {
                "Name": "busy_payne",
                "EndpointID": "0c9f919e4f225233ee3265e63f70c60fd04b022d4f4ba732f8b35ce50f37b355",
                "MacAddress": "02:42:ac:11:20:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "29a8bbacdc838ebe412d80709d049548fe0d7ece13fb283dfe8364063cb71eca": {
                "Name": "eloquent_hypatia",
                "EndpointID": "0dce3538f4771bfd50877a88c4db14ecb535d7aa1494e0a799d0a3cf59b43d1c",
                "MacAddress": "02:42:ac:11:30:05",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            },
            "4e4d789f0f6d3327e761ca3910671a98750bce28d4574fa34e298d67ffa9f718": {
                "Name": "AutoBangumi",
                "EndpointID": "b4dd06b57917bfb871e0f2c8a61e80c89f29f95320ec84730a305ef73d27cce3",
                "MacAddress": "02:42:ac:11:40:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "5f33c7d12d011c91e03fb1256b64063e2b0782bcb555c838aeeb5c0923efcace": {
                "Name": "cranky_blackburn",
                "EndpointID": "3d3712f8930b450b0b22e7116b931cd31be6ffe8f965818fc5394660b2e76ffa",
                "MacAddress": "02:42:ac:11:50:06",
                "IPv4Address": "172.17.0.6/16",
                "IPv6Address": ""
            },
            "fe6a4448cf034a2304d70147829cf5118efb955b6219f6a1046b746aa3d0de2b": {
                "Name": "gotify",
                "EndpointID": "602a1b90c40aa5926cb8ace43f7275217a820d46a20fa52bf1a75a13da1326ca",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "65535"
        },
        "Labels": {}
    }
]
➜  autobangumi docker network inspect e6b816c0a9bd
[
    {
        "Name": "qbittorrent_default",
        "Id": "e6b816c0a9bd76bcce75068dfbb592fb294a4afa85b88ee31585d8c27bab39f2",
        "Created": "2023-09-26T19:36:45.48475162Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7a9287bb5dfe1fef498fac2fc3ef4976a2af469a7ae3f07c1519380cda62c9ff": {
                "Name": "qbittorrent",
                "EndpointID": "7d04e5b9a8709c62cdfd2ceac2a94d1860de2e3db1bf16386d2607d620d5884a",
                "MacAddress": "02:42:dc:13:04:12",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "qbittorrent",
            "com.docker.compose.version": "2.21.0"
        }
    }
]
```
