### ISSUE TITLE
[错误报告]快速开始中的Docker compose文件 拉起失败 service "qbittorrent" refers to undefined network host: invalid compose project

### ISSUE THREAD

**Issue by saltfish13** [EstrellaXD/Auto_Bangumi#599]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

其他问题

### 问题描述

尝试使用快速开始中实例的docker compose文件进行 fresh install时发生错误，无法正常拉起
实例yaml文件：https://raw.githubusercontent.com/EstrellaXD/Auto_Bangumi/main/docs/resource/docker-compose/qBittorrent+AutoBangumi/docker-compose.yml
我的修改如下
version: "3.4"
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    hostname: qbittorrent
    environment:
      - PGID=1900 #需要自行修改填入
      - PUID=990 #需要自行修改填入
      - WEBUI_PORT=8989
      - TZ=Asia/Shanghai
    volumes:
      - /D/Auto Bangumi/qb_config:/config
      - /D/File Server/动漫:/downloads
    networks:
      - host
    restart: unless-stopped

  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    depends_on:
      - qbittorrent
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - host
    dns:
      - 223.5.5.5
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - AB_METHOD=Advance
      - PGID=900 #需要自行修改填入
      - PUID=9000 #需要自行修改填入
      - UMASK=022
      - AB_DOWNLOADER_HOST=127.0.0.1:8989 #如8989被修改,请修改为相应端口
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_DOWNLOAD_PATH=/downloads #qbittorrent 映射的地址，否者可能提示下载失败

报错无法正常拉起
service "qbittorrent" refers to undefined network host: invalid compose project

### 发生问题时系统日志

```bash
service "qbittorrent" refers to undefined network host: invalid compose project
```

**Comment by codycjy** [comment]
```yaml
  AutoBangumi:
    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
    container_name: AutoBangumi
    depends_on:
      - qbittorrent
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    network_mode: host
    dns:
      - 223.5.5.5
```
可以试下这样子配置
但是windows docker并不支持host网络
