### ISSUE TITLE
[Checker] Downloader connect failed.

### ISSUE THREAD

**Issue by winnower-sliff** [EstrellaXD/Auto_Bangumi#684]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.12

### 问题类型

程序运行问题

### 问题描述

通过 Docker Compose 部署 AutoBangumi
同时安装 qBittorrent 与 AutoBangumi的镜像
提示：
```
ERROR     [Checker] Downloader connect failed.
WARNING:  Program failed to start.
```
此时无法通过任何一种ip访问7892端口，即无法打开WebUI

### 发生问题时系统日志

```bash
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Started server process [6]
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Waiting for application startup.
AutoBangumi  | [2024-02-01 01:47:57] INFO:     
AutoBangumi  | [2024-02-01 01:47:57] INFO:                     _        ____                                    _
AutoBangumi  | [2024-02-01 01:47:57] INFO:          /\        | |      |  _ \                                  (_)
AutoBangumi  | [2024-02-01 01:47:57] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
AutoBangumi  | [2024-02-01 01:47:57] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
AutoBangumi  | [2024-02-01 01:47:57] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
AutoBangumi  | [2024-02-01 01:47:57] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
AutoBangumi  | [2024-02-01 01:47:57] INFO:                                                 __/ |
AutoBangumi  | [2024-02-01 01:47:57] INFO:                                                |___/
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Version 3.1.12  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
AutoBangumi  | [2024-02-01 01:47:57] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Starting AutoBangumi...
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Config loaded
AutoBangumi  | [2024-02-01 01:47:57] ERROR     [Checker] Downloader connect failed.
AutoBangumi  | [2024-02-01 01:47:57] WARNING:  Program failed to start.
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Application startup complete.
AutoBangumi  | [2024-02-01 01:47:57] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
```

**Comment by winnower-sliff** [comment]
yml文件：
```
version: "3.4"
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    hostname: qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./qb_config:/config
      - /home/share/movie:/downloads # 注意 修改此处为自己存放动漫的目录,ab 内下载路径填写downloads
    network_mode: bridge
    restart: unless-stopped

  AutoBangumi:
    image: "ghcr.nju.edu.cn/estrellaxd/auto_bangumi:3.1.12"
    container_name: AutoBangumi
    depends_on:
      - qbittorrent
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    network_mode: bridge
    dns:
      - 223.5.5.5
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PGID=1000
      - PUID=1000
      - UMASK=022
```
config.json:
```
{
    "program": {
        "rss_time": 900,
        "rename_time": 60,
        "webui_port": 7892
    },
    "downloader": {
        "type": "qbittorrent",
        "host": "172.17.0.1:8080",
        "username": "admin",
        "password": "adminadmin",
        "path": "/downloads/Bangumi",
        "ssl": false
    },
    "rss_parser": {
        "enable": true,
        "filter": [
            "720",
            "\\d+-\\d"
        ],
        "language": "zh"
    },
    "bangumi_manage": {
        "enable": true,
        "eps_complete": false,
        "rename_method": "pn",
        "group_tag": false,
        "remove_bad_torrent": false
    },
    "log": {
        "debug_enable": false
    },
    "proxy": {
        "enable": false,
        "type": "http",
        "host": "",
        "port": 0,
        "username": "",
        "password": ""
    },
    "notification": {
        "enable": false,
        "type": "telegram",
        "token": "",
        "chat_id": ""
    },
    "experimental_openai": {
        "enable": false,
        "api_key": "",
        "api_base": "https://api.openai.com/v1",
        "api_type": "openai",
        "api_version": "2023-05-15",
        "model": "gpt-3.5-turbo",
        "deployment_id": ""
    }
}
```
