### ISSUE TITLE
Windows 10/11 WSL2 环境docker-compose 示例

### ISSUE THREAD

**Issue by onlylhf** [EstrellaXD/Auto_Bangumi#73]
经过几天折腾总算可以在Windows的wsl下运行Auto_Bangumi了，分享一下使用 docker-compose.yml

```yml
version: "3.6"
services:
  qbittorrent:
    container_name: qbittorrent
    image: johngong/qbittorrent:latest
    hostname: qBittorrent
    environment:
      - QB_EE_BIN=false
      - UID=1000  # 用户权限1000 当前WSL登录用户，查询方法 wsl内输入 id 用户名
      - GID=1000
      - QB_WEBUI_PORT=8989
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8989:8989
    volumes:
      - qb_config:/config
      - /mnt/g/animation:/Downloads   #下载路径，对应 Windows上目录是 G:\animation
    networks:
      - AutoBangumi_network
    restart: unless-stopped

  AutoBangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: AutoBangumi
    ports:
      - 7892:7892
    depends_on:
      - qBittorrent
    volumes:
      - auto_bangumi:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - AB_DOWNLOADER_HOST=qBittorrent:8989
      - AB_DOWNLOADER_USERNAME=admin 
      - AB_DOWNLOADER_PASSWORD=adminadmin 
      - AB_INTERVAL_TIME=1800
      - AB_RENAME_FREQ=10
      - AB_METHOD=Advance
      - AB_GROUP_TAG=True
      - AB_NOT_CONTAIN=720|繁体|CHT|JPTC|繁日|BIG5
      - AB_DOWNLOAD_PATH=/Downloads  #qBittorrent 映射的地址，否者可能提示下载失败
      - AB_RSS=https://mikanani.me/RSS/MyBangumi?token=xxxxxxxx%3d%3d  #订阅地址，改成自己的
      - AB_DEBUG_MODE=False
      - AB_EP_COMPLETE=True
      - AB_WEBUI_PORT=7892
      - AB_RENAME=True
      - AB_ENABLE_TMDB=True
      - AB_LANGUAGE=zh
    networks:
      - AutoBangumi_network
    restart: unless-stopped

networks:
  AutoBangumi_network:
volumes:
  qb_config:
    external: false
  auto_bangumi:
    external: false

```
