### ISSUE TITLE
[重命名错误] windows qb 存在重命名问题

### ISSUE THREAD

**Issue by Rewrite0** [EstrellaXD/Auto_Bangumi#809]
### 当前程序版本

3.1.14

### 重命名设置

advance

### 种子名称

[Nekomoe kissaten&LoliHouse] Monogatari Series - Off & Monster Season - 02 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 

### 文件路径

Z:\Download\qBittorrent\番剧\物语系列 (2009)\Season 5

### 错误命名

无法重命名

### 发生问题时系统日志

```shell
INFO
[2024-07-18 10:10:42]
[Nekomoe kissaten&LoliHouse] Monogatari Series - Off & Monster Season - 02 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv >> Z:\Download\qBittorrent\番剧\物语系列 (2009)\Season 5 S01E02.mkv
DEBUG
[2024-07-18 10:10:42]
Conflict409Error: [Nekomoe kissaten&LoliHouse] Monogatari Series - Off & Monster Season - 02 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv >> Z:\Download\qBittorrent\番剧\物语系列 (2009)\Season 5 S01E02.mkv
DEBUG
[2024-07-18 10:10:42]
[Renamer] Rename process finished.
```
```

**Comment by Rewrite0** [comment]
qb 为 windows 平台.
重命名无法完成，并导致一直循环重命名.

**Comment by PokeLu** [comment]
使用win server 2022H遇到相同问题，一直持续重命名

**Comment by xfrqh** [comment]
为了解决这个问题，我转向Linux了。😋

这是我的qb的docker compose文件，适用于Ubuntu。其中的挂载卷和身份，按需修改。

如果你需要qb有**单独的IP**，那么可能需要用到**macVLAN**网络。修改其中的宿主机的网卡名、IPv4地址、IPv4子网即可。

```yaml
version: "3.5"
services:
  qBittorrentEE:
    container_name: qBittorrentEE
    image: superng6/qbittorrentee

    # network_mode: 'host'
    networks:
      qbittorrent_net:
        ipv4_address: 192.168.7.21

    volumes:
      - /app/qbittorrent/:/config/qBittorrent/
      - mynfs:/mnt/nfs

    restart: unless-stopped
    environment:
      - PUID=07 # NAS中的用户名和用户组
      - PGID=21

      - WEBUIPORT=5052 # WEB 管理平台端口
      - TZ=Asia/Shanghai # 时区

  PeerBanHelper:
    image: ghostchu/peerbanhelper:v5.1.0
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - /app/PeerBanHelper:/app/data
    ports:
      - "9898:9898"
    environment:
      - TZ=Asia/Shanghai # 时区

networks:
  qbittorrent_net:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ens34
      gateway: 192.168.7.1
      ipv6_gateway: fd0d:7eb5:2afd::1
    ipam:
      config:
        - subnet: 192.168.7.0/24
        - subnet: fd0d:7eb5:2afd::/64

volumes:
  mynfs:
    external: true

```
